name: pangeo
channels:
  - conda-forge
dependencies:
  - cc-plugin-ncei
  - ciso
  - compliance-checker
  - ctd
  - geolinks
  - gridgeo
  - ioos-tools
  - nc-time-axis
  - pocean-core
  - podaacpy
  - pyoos
  - retrying
  - unyt
  - utide
  - xlrd
  - nbdime
  - xlayers
  - pip 
  - pip:
    - git+https://github.com/xgcm/xgcm.git@master
    - git+https://github.com/intake/filesystem_spec.git@master
    - git+https://github.com/dask/gcsfs.git@master
    - git+https://github.com/intake/gdrivefs.git@master
    - git+https://github.com/NCAR/intake-esm.git
    - git+https://github.com/MITgcm/xmitgcm.git
